version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/web-template
    docker:
      - image: cimg/openjdk:17.0.6
    steps:
      - checkout
      - restore_cache:
          key: web-template-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline -P code-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: web-template-{{ checksum "pom.xml" }}
      - run: mvn clean install -P code-coverage
      - store_test_results:
          path: target/surefire-reports
      - codecov/upload:
         file: target/jacoco-report/jacoco.xml
         token: $CODECOV_TOKEN

